#!/usr/bin/env zsh

colorR="\e[38;5;1m"
colorG="\e[38;5;2m"
colorB="\e[38;5;4m"
colorW="\e[38;5;7m"
bold="\033[1m"
bold_reset="\033[0m"
reset="\e[0m"

error_msg() {
    printf "%b" "${colorR}Error: ${colorW}${1}${reset}\n"
}

status_msg() {
    printf "%b" "${colorG}${1}${reset}\n"
}

status_msg "Checking OS"

system=$(uname -s)
printf "%b" "${colorB}Looks like ${colorW}${bold}${system}${bold_reset}${reset}\n"

if [[ ! -e "$HOME/.config/.bootstrap-done" ]]; then
    status_msg "Getting all dependencies"
    mkdir -p ~/.local/share/icons ~/.local/share/themes

    pushd ~/.config || exit 1
    git clone https://github.com/elken/nvim
    if [ "$system" = "Linux" ]; then
        git clone https://github.com/ccuqme/swarofi-updater.git
        chmod +x swarofi-updater/*.sh
    fi
    popd || exit 1
    if [ "$system" = "Linux" ]; then
        git clone https://github.com/elken/Nordic ~/.local/share/themes/Nordic
    fi

    status_msg "Moving to SSH"
    yadm remote set-url origin "git@github.com:elken/.files"

    status_msg "Sourcing shell config"
    source "$HOME/.config/zsh/.zprofile"

    if ! command -v brew >/dev/null 2>&1; then
        if [ "$system" = "Darwin" ]; then
            status_msg "Homebrew not installed, installing now"
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        elif [ "$system" = "Linux" ]; then
            status_msg "Linuxbrew not installed, installing now"
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        fi
    fi
    status_msg "Processing yadm templates"
    yadm alt

    status_msg "Installing Homebrew packages"
    brew bundle --file="$HOME/.config/yadm/Brewfile"

    status_msg "Locking sheldon plugins"
    sheldon lock

    if ! command -v flatpak >/dev/null 2>&1; then
        flatpak remote-delete fedora --force
        # shellcheck disable=SC2046
        flatpak install --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1)
        flatpak install --noninteractive flathub org.mozilla.firefox org.mozilla.Thunderbird org.libreoffice.LibreOffice com.github.tchx84.Flatseal com.slack.Slack com.spotify.Client io.podman_desktop.PodmanDesktop net.lutris.Lutris org.inkscape.Inkscape org.kde.kdenlive org.videolan.VLC
    fi

    rm -rf "$HOME/.config/sway/config.d/99-firstboot.conf"
    touch "$HOME/.config/.bootstrap-done"
else
    status_msg "Already ran, if this is an error remove $HOME/.config/.bootstrap-done"
fi
