theme = "nord-lkn"

[editor]
line-number = "relative"
auto-save = true
completion-replace = true
undercurl = true
true-color = true
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "register"]
center = ["file-type", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["selections", "file-encoding", "position"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.normal]
C-s = ":w!"
C-u = ["half_page_up", "goto_window_center"]
C-d = ["half_page_down", "goto_window_center"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
D = ["extend_to_line_end", "delete_selection"]
X = "extend_line_above"
# One to toy around with, I prefer the behaviour but I feel like it's a smell
# esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space".c]
f = ":open ~/.config/helix"
r = [":config-reload", ":reload-all"]

[keys.normal.space]
space = "file_picker_in_current_buffer_directory"
f = "file_picker"
z = [
  "goto_first_nonwhitespace",
  "extend_to_line_end",
  ":pipe-to xargs -d'\n' -I {} -- zellij r -f -- zsh -c '{}'"
]

[keys.normal.space.b]
b = "buffer_picker"
n = "goto_next_buffer"
p = "goto_previous_buffer"
d = ":buffer-close"

[keys.normal.space.o]
g = ":sh zrf yl"
t = ":sh zrf"

[keys.normal.g]
a = "code_action"
q = ":reflow"
g = ":sh zrf lazygit"
t = "goto_file_start"
T = "goto_window_top"

[keys.select]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
