[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "(elixir|ex)"
file-types = ["ex", "exs", "html.heex"]
shebangs = ["elixir"]
roots = ["mix.exs"]
auto-format = true
diagnostic-severity = "Hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-servers = ["elixir-ls"]

[language-server.tailwind-heex]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "elixir"
language-id = "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls", "vscode-html-language-server"]
auto-format = true

[[language]]
name = "heex"
scope = "source.heex"
injection-regex = "heex"
language-id= "phoenix-heex"
language-servers = ["tailwind-heex", "elixir-ls", "vscode-html-language-server"]
comment-token = "<%!--"
auto-format = true
