[language-server.tailwind-heex]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "elixir"
file-types = ["ex", "exs", "html.heex"]
auto-format = true
diagnostic-severity = "Hint"

# [[language]]
# name = "elixir"
# language-id = "phoenix-heex"
# language-servers = ["tailwind-heex", "elixir-ls", "vscode-html-language-server", "emmet-ls"]
# auto-format = true

[[language]]
name = "heex"
language-servers = ["tailwind-heex", "elixir-ls", "vscode-html-language-server", "emmet-lsp"]
auto-format = true
